all: triInsertion triFusion triRapide

triInsertion: triInsertion.c
	gcc -o bin/triInsertion -Wall triInsertion.c

trFusion: triFusion.c
	gcc -o bin/triFusion -Wall triFusion.c

triRapide: triRapide.c
	gcc -o bin/triRapide -Wall triRapide.c
