all: triInsertion triFusion triRapide triFusionInsertion

triInsertion: algos/triInsertion.c
	gcc -o bin/triInsertion -Wall algos/triInsertion.c

triFusion: algos/triFusion.c
	gcc -o bin/triFusion -Wall algos/triFusion.c

triRapide: algos/triRapide.c
	gcc -o bin/triRapide -Wall algos/triRapide.c

triFusionInsertion: algos/triFusionInsertion.c
	gcc -o bin/triFusionInsertion -Wall algos/triFusionInsertion.c
